database: # база данных MySQL
  user: "root"
  port: "3036"
  db: "reputation"
  password: "password"

defaultmaximum: 90 # (Максимальный уровень, который можно получить без доната)

## Уровни и их левел (доступно редактирование)
levels:
  100: "Мессия"
  90: "Ангел"
  80: "Последняя надежда"
  70: "Спаситель"
  60: "Чудо Господне"
  50: "Посол Доброй Воли"
  40: "Защитник"
  30: "Миротворец"
  20: "Искатель"
  10: "Гражданин"
  0: "Нейтрал"
  -10: "Бродяга"
  -20: "Авантюрист"
  -30: "Мародёр"
  -40: "Предатель"
  -50: "Подонок"
  -60: "Бич человечества"
  -70: "Воплощение зла"
  -80: "Демонское отродье"
  -90: "Сын Иуды"
  -100: "Дьявол"
  